name: GitHub Actions Pull
run-name: ${{ github.actor }} is testing when open pull request 🚀
on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-and-build:
    # strategy:
    #   matrix:
    #     version: [16, 18]
    #     os: [ubuntu-latest, windows-latest]
    # runs-on: ${{ matrix.os }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node enviroment
        uses: actions/setup-node@v3
        with:
          # node-version: ${{ matrix.version }}
          node-version: 18
          cache: "yarn"
          cache-dependency-path: yarn.lock

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run Test
        run: yarn run test

      - name: Run Build
        run: yarn run build
